SemanticMediaWiki/SemanticResultFormats

- formats/calendar/SRF_Calendar.php
- i18n/de.json
- i18n/en.json
I needed SRF Calendar to show a specific month/year instead of the current one. So I implemented two new parameter: startmonth and startyear. Both defaults to current values if not specified.
> [Calendar] added startmonth and startyear parameter

- formats/calendar/resources/ext.srf.formats.eventcalendar.js
- If the length of the event description <= self.defaults.descriptionLength, we shouldn't process it to be shortened.
- The tooltip failed to display event descriptions having no space characters within. It matters when we deal with CJK texts.
> minor fix of tooltip for month view

- Resources.php
- formats/Filtered/SRF_Filtered.php
- formats/Filtered/SRF_Filtered_Item.php
- formats/Filtered/libs/ext.srf.filtered.table-view.js
- formats/Filtered/views/SRF_FV_Table.php
- i18n/de.json
- i18n/en.json
At gesinn.it, we've been working internally with a "table" view enhancement for the filtered view since a while. Our customers love it. We've polished it a bit and merged it with a recent version of SRF.
Format is tested on MW 1.25.2, SMW 2.2.2. No issues.
We'd like to contribute this back to SRF so that others can use it...
> [SRF][Filtered] New view 'table' added

- SemanticResultFormats.php
If another composer-installed extension (e.g. Semantic Extra Special Properties) installs Semantic MediaWiki in its local extension vendor directory, Semantic MediaWiki will be autoloaded from there, but the files for this extension will never be autoloaded (because SMW_VERSION will already be defined). Perhaps there is a better solution, but with this change, if composer is run in the SemanticResultFormats directory to create its local vendor directory, the code will now be sure to autoload the files for this extension.
> Fix for running composer locally

- formats/media/resources/ext.srf.formats.media.js
[0] http://wikimedia.7.x6.nabble.com/Semantic-Result-Formats-Media-Format-Loading-Forever-td5057523.html
> Avoid access of `this` for video in format=media

- SemanticResultFormats.parser.php
Prior to being input to mktime(), the $lower_day variable was not always being set. The major cause of this was that $lower_month was being set to $default_day, instead of setting $lower_day to its default.
Additionally, there was some confusing logic surrounding $lower_day, which was cleaned up.
Closes #153
> Fix missing $lower_day assignments; cleanup

- RELEASE-NOTES.md
- formats/Filtered/libs/ext.srf.filtered.js
Chrome 51+ and Firefox 48+ support the Array.prototype.values() method, which clashes with the 'values' parameter of the value filter. So we have to make sure, that when accessing that field we really get a string (i.e. something we set ourselves) and not a function (provided in the Array prototype).
See https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/values
> Filtered format: Fix Uncaught TypeError: fixedValues.split is not a function

- formats/Filtered/libs/ext.srf.filtered.value-filter.js
This pull request is a proper version of the  #144 pull request.
It introduces support for displaytitle labels for the filters itself in the filtered format, given that at least SMW >= 2.4 is used. If SMW is of a lower version, this patch will fall back to use the ID as the label.
When testing, I found one catch: When `link=none` is used, no label can be detected, as it is extracted for the `formatted value` `<a>` tag. In that case there is no way for the result format to know what the label should have been.
This pull request also fixes a potential issue with the alphabetical ordering of the filters. Previously an object (dictionary) was used. Those do not guarantuee the order of their keys. Most browsers keep the order until a certain size, but after that they will shuffle it up.
Best, …
> Add displaytitle label support to filtered format, fix sorting order

- .travis.yml
- tests/bootstrap.php
- tests/phpunit/Integration/JSONScript/JsonTestCaseScriptRunnerTest.php
- tests/phpunit/Integration/JSONScript/README.md
- tests/phpunit/Integration/JSONScript/TestCases/bootstrap.json
This PR is made in reference to: #220
This PR adds minimum JSONScript integration test support to Semantic Result Formats.
> Add integration testing using JSONScript

- SemanticResultFormats.php
- composer.json
This PR is made in reference to: #190 
- Starts the development of SRF 3.0.0 on master since 2.5.x is now on its own branch
> Start 3.0.0 development version

- formats/tree/TreeResultPrinter.php
- tests/phpunit/Integration/JSONScript/TestCases/tree-01.json
This PR is made in reference to: #234 
- Make `tree-01.json` fail when #234 present
- Actually use `<ol>` when `format=oltree`
> Fix #234: Use <ol> when format=oltree

- formats/tree/TreeResultPrinter.php
- tests/phpunit/Integration/JSONScript/TestCases/tree-02.json
- tests/phpunit/Integration/JSONScript/TestCases/tree-06.json
This PR is made in reference to: #235 
- Make `tree-02.json` and `tree-06.json` fail when #235 present
- Fix template parameter
> Fix #235: template option works again

- formats/math/SRF_Math.php
- tests/phpunit/Integration/JSONScript/TestCases/math-01.json
This PR is made in reference to: #248
- Use `NumberValue::getLocalizedFormattedNumber` to get the localized format according to settings available
- Cannot be back-ported to SRF 2.5.x (as that would allow SMW 2.1) [0] because the change requires at least SMW 2.4.x
[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/2.5.x/composer.json#L50
> Math format to use getLocalizedFormattedNumber, refs 248

- .travis.yml
- INSTALL.md
- README.md
- RELEASE-NOTES.md
- build/travis/install-semantic-result-formats.sh
- composer.json
This PR is made in reference to: #259 
This PR updates dependencies for the upcoming SRF 3.0 and updates the test matrix accordingly.
> Update dependencies for upcoming SRF 3.0

- .travis.yml
- RELEASE-NOTES.md
The configuration allowed to fail needs to be listed among the configurations to be included in the tests as well.
> Fix travis build matrix to actually run allowed failures

- tests/phpunit/Integration/JSONScript/TestCases/tree-01.json
- tests/phpunit/Integration/JSONScript/TestCases/tree-02.json
- tests/phpunit/Integration/JSONScript/TestCases/tree-04.json
- tests/phpunit/Integration/JSONScript/TestCases/tree-06.json
- tests/phpunit/Integration/JSONScript/TestCases/tree-07.json
- Switch `tree` format JsonScript integration tests to use type `parser-html` instead of `parser` to test the html structure of the output rather exact equality of strings
> Tree format: Use type `parser-html` for JsonScript tests

- .travis.yml
- build/travis/run-tests.sh
- phpunit.xml.dist
- tests/phpunit/Unit/Formats/TreeTest.php
This PR addresses enables test coverage reporting.
Before this is merged somebody should enable external code coverage on Scrutinizer. See https://scrutinizer-ci.com/docs/tools/external-code-coverage/
> Enable test coverage reports

- formats/calendar/resources/ext.srf.formats.eventcalendar.js
Fixed syntax error in onDayClick function declaration.
When using the eventCalendar result format IE users are presented with an infinite loading spinner. 
The reason for this is that the JS function definition for the function "onDayClick" is syntactically incorrect and causes IE to choke. Specifically, it currently looks like:
`onDayClick( date, data, clickPopup )`
when it should instead be:
`onDayClick: function( date, data, clickPopup )`
> Fixed calendar rendering in IE

- Resources.php
- formats/timeline/SRF_Timeline.php
- formats/timeline/resources/ext.srf.timeline.js
- tests/phpunit/Integration/JSONScript/TestCases/timeline-01.json
This PR is made in reference to: #292, https://sourceforge.net/p/semediawiki/mailman/message/36008850/
- https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/9a2d405d28e18ef50cdda12996d3b260c29e2127 tried to tackle the loading issue in the past but it is believed that recent changes to the ResourceLoader requires a different approach
- Load each file explicitly as outlined in `timeline-api.js`
- Create a `Timeline` instance only after resources have been loaded to avoid a "Timeline.DefaultEventSource is not a constructor"
- Removes the misplaced  `srf-timeline-allresults` with the further results link as is shown even though the JS isn't loaded given a false impression on the current result display or where no further results are available.
- …
> Timeline, fix resource loading

- formats/timeline/SRF_Timeline.php
- formats/timeline/resources/ext.srf.timeline.js
This PR is made in reference to: #294
Fixes: #294
> Timeline, fix subobject issues, refs 294

- tests/phpunit/Integration/JSONScript/TestCases/filtered-02.json
This PR is made in reference to: # https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2691
- The particular type now carries the correct `Warning` label with an error severity denoting a different code 
> Fix filtered-02.json integration test

- formats/calendar/EventCalendar.php
- formats/calendar/resources/ext.srf.formats.eventcalendar.js
- formats/datatables/DataTables.php
- src/ResourceFormatter.php
- tests/phpunit/Integration/JSONScript/TestCases/datatables-01.json
- tests/phpunit/Integration/JSONScript/TestCases/eventcalendar-01.json
- tests/phpunit/Unit/ResourceFormatterTest.php
This PR is made in reference to: #317 
- Removes the deprecated `ApiResultPrinter` and moves required methods to a local `ResourceFormatter` (maybe there is a better name but for the 10 min. I worked on this, nothing popped my mind)
- Fixes #317  through the use of `ResourceFormatter`
- Adds a simple integration tests for `format=datatables` and `format=eventcalendar` to detect issues like an incompatible method access that caused #317
Fixes: #317
> Remove deprecated ApiResultPrinter, refs 317

- formats/Exhibit/exhibit/extensions/map/map-extension-bundle.css
- formats/Exhibit/exhibit/extensions/map/styles/olmap-view.css
- Some assets in Exhibit are always loaded over HTTP. This can cause mixedcontent issues if the wiki is using HTTPS. This change ensures the assets are always loaded over HTTPS.
> Load exhibit map assets over HTTPS

- formats/time/SRF_Time.php
- tests/phpunit/Integration/JSONScript/TestCases/earliest-01.json
- tests/phpunit/Integration/JSONScript/TestCases/latest-01.json
This PR is made in reference to: #344
Fixes: #344
> Remove `default` from earliest, latest, refs 344

- tests/phpunit/Integration/JSONScript/TestCases/tagcloud-02.json
This PR is made in reference to: #356 
- Adds #356 missing integration test for `format=tagcloud` using the `NS_HELP` namespace
> Follow-up, tagcloud integration test, refs 356

- Resources.php
- i18n/en.json
- i18n/qqq.json
This PR is made in reference to: -
- srf-error-jqplot-bubble-data-length was missing (added in bfe3e83a but not defined)
- smw_qui_limt is unused in SRF and removed from SMW since 6f7625f
> Maintenance on messages

- RELEASE-NOTES.md
- formats/graphviz/SRF_Graph.php
This PR is made in reference to: https://phabricator.wikimedia.org/T181926
- Adds extra check for whether the GraphViz extension is loaded.
- Parses the graphviz source in a more future-compatible way (i.e. the `<graphviz>` element, rather than directly calling the render method).
> Update for new GraphViz extension class structure

- formats/calendar/SRF_Calendar.php
- i18n/en.json
- i18n/qqq.json
This PR is made in reference to: #353 
- reuses "smw-paramdesc-template" and "smw-paramdesc-userparam" for the missing "srf-paramdesc-userparam" and "srf-paramdesc-template" which is acceptable since SRF is directly dependant on SMW
- adds "srf-paramdesc-color" including documentation 
> Provide missing system messages

- formats/googlecharts/README
- formats/googlecharts/SRF_GoogleBar.php
- formats/googlecharts/SRF_GooglePie.php
This PR is made in reference to: #378 
- Makes Google pie format use the Google Chart API via https
- Makes Google chart format use the Google Chart API via https
- Updates the respective documentation
Fixes #378
> Fixes result printers still using the Google Chart API via http

- formats/filtered/resources/css/ext.srf.filtered.value-filter.less
Remove selector for .select2-container .select2-search--inline, which was causing select2 elements to render incorrectly.
This PR is made in reference to: #373
> Filtered format: select2 list elements rendering outside of containing element

- formats/filtered/src/Filtered.php
This PR is made in reference to: #362
- Remove calls to ResultPrinter::getParser()
- Remove calls to ResultPrinter::getOutput()
> Remove/replace calls to ResultPrinter::getParser() and ::getOutput()

- formats/filtered/package-lock.json
- formats/filtered/package.json
- formats/filtered/resources/js/ext.srf.filtered.select.js
This PR is made in reference to: #383 
Lock Select 2 to v4.0.3, 4.0.4 onwards is broken
See https://github.com/select2/select2/commit/45a877345482956021161203ac789c25f40a7d5e
> Filtered: Lock Select 2 to v4.0.3 (Backport to 2.5.x)

- RELEASE-NOTES.md
- formats/gallery/Gallery.php
This PR is made in reference to: #375 
- Fixes "gallery" exposing file dimensions in captions // Code as suggested in https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/375#issuecomment-367768383
Fixes #375
> Fixes "gallery" exposing file dimensions in captions

- RELEASE-NOTES.md
- formats/tree/TreeNodeVisitor.php
- formats/tree/TreeResultPrinter.php
The 'template arguments' parameter was introduced for compatibility and can be removed in SRF 3.0
> Remove 'template arguments' parameter

- formats/gallery/Gallery.php
* Remove feature switch, always use TraditionalImageGallery now
* Fix a potential 'method not found' warning
* Fix inline documentation
Fixes #229
> Gallery: Remove feature switch, always use TraditionalImageGallery

- formats/outline/SRF_Outline.php
- src/Outline/README.md
- src/Outline/TemplateBuilder.php
- tests/phpunit/Integration/JSONScript/TestCases/outline-01.json
- tests/phpunit/Unit/Outline/TemplateBuilderTest.php
This PR is made in reference to: #88 
- Adds the `template` parameter and `TemplateBuilder` to create individual hierarchical output lists using a template
- `named args` are `true` by default and I haven't considered implementing numerical parameter (aka `{{{1}}}`) support in the `TemplateBuilder` (which means it is missing by design and if required someone should send a patch and test)
- Adds `outline-01.json` integration test to verify that the `template` produces a specified output
- The format hasn't seen any updates in years and this PR fixes a notorious "Notice: Array to string conversion in .../w/extensions/SemanticMediaWiki/includes/SMW_Infolink.php on line 469" caused by the wrong use of `$link = $res->getQueryLink(); / $link->setParameter( …
> Add `template` to outline format, refs 88

- formats/outline/SRF_Outline.php
- src/Outline/ListTreeBuilder.php
- src/Outline/OutlineItem.php
- src/Outline/OutlineTree.php
- src/Outline/TemplateBuilder.php
- tests/phpunit/Integration/JSONScript/TestCases/outline-02.json
- tests/phpunit/Unit/Outline/ListTreeBuilderTest.php
- tests/phpunit/Unit/Outline/OutlineItemTest.php
- tests/phpunit/Unit/Outline/OutlineTreeTest.php
This PR is made in reference to: #457
- Just some clean-ups some issues I found while working on #457
- Moves `SRFOutlineItem` (part of `SRF_Outline.php`) to `OutlineItem` + rudimentary test
- Moves `SRFOutlineTree` (part of `SRF_Outline.php`) to `OutlineTree` + a rudimentary test
- Moves tree building code to `ListTreeBuilder` + rudimentary test
- Adds `outline-02.json` integration test to validate the list ouput
- Fixes `link=...` which wasn't working at all
Fixes #
> Tidy (Outline format), refs 457

- formats/widget/SRF_ListWidget.php
- tests/phpunit/Integration/JSONScript/TestCases/listwidget-01.json
This PR is made in reference to: #449 
- Remove internal interface `mFormat` that does not exist anymore
Fixes #449
> ListWidget: Remove usage of `$this->mFormat` (not taken into account anymore by parent class)

- .travis.yml
This PR is made in reference to: #467
- Re-enable master as voting setup in CI tests
Fixes #
> Re-enable master as voting test setup

- .travis.yml
Reverts SemanticMediaWiki/SemanticResultFormats#484
This just invites trouble has seen by https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3914, https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3915, https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3916 and I don't have the time deal with this any time soon.
> Revert "Re-enable master as voting test setup"

- RELEASE-NOTES.md
- formats/timeseries/resources/ext.srf.timeseries.flot.js
This PR is made in reference to: #400 
- Fix Timeseries format: `uncaught exception: Invalid dimensions for plot` 
Fixes #400
> Timeseries format: Only correct plot height when there are tabs

- formats/graphviz/SRF_Graph.php
- i18n/en.json
- i18n/qqq.json
- Adds `nodelabel` parameter with `displaytitle` option based on [DISPLAYTITLE](https://www.mediawiki.org/wiki/Extension:Display_Title). It allows to display correct page titles on graph nodes.
> Add `nodelabel` parameter with `displaytitle` option

- tests/phpunit/Integration/ResourcesTest.php
This PR is made in reference to: #501
Fixes #501
> [CI] Fix `ResourceLoader` construction (MW 1.33+), refs 501

- src/vCard/vCardFileExportPrinter.php
- tests/bootstrap.php
- tests/phpunit/ResultPrinterReflector.php
- tests/phpunit/Unit/vCard/vCardFileExportPrinterTest.php
This PR is made in reference to: #371
- Adds `filename` as parameter to the `format=vcard`
Fixes #371
> Add `filename` to `format=vcard`, refs 371

- formats/filtered/src/View/MapView.php
This check was still using the old class name which got removed some time ago. Hence this code was broken on modern PHP versions.
Removed the check altogether in second commit since there is no need for it.
> Fix bug in MapView format

- Resources.php
This provides addOnloadHook() and importScript/importStyles functions,
none of which are used here.
> Remove unused mediawiki.legacy.wikibits dependency

- src/iCalendar/DateParser.php
- src/iCalendar/iCalendarFileExportPrinter.php
- tests/phpunit/Unit/iCalendar/DateParserTest.php
- Isolates the date parsing and moves it into a separate class, adds a unit test, and fixes a copy-paste error `DataValueFactoryg::getInstance`
> [ical] Add `DateParser`

- src/iCalendar/DateParser.php
- src/iCalendar/IcalFormatter.php
- src/iCalendar/iCalendarFileExportPrinter.php
- tests/phpunit/Unit/iCalendar/DateParserTest.php
- tests/phpunit/Unit/iCalendar/IcalFormatterTest.php
This PR is made in reference to: #340
- Isolates the ical specific output formatting and moves it to a separate class that can be tested autonomously.
> [ical] Add `IcalFormatter`, refs 340

- tests/phpunit/Integration/JSONScript/Fixtures/bibtex-sequence-map.json
- tests/phpunit/Integration/JSONScript/TestCases/bibtex-01.json
This PR is made in reference to: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4226
- This is an example for the use of a "sequence map", while MySQL/MariaDB, and SQLite do return a specific sequence by default, PostgreSQL would fail that assumption and the test as well
- After adding a `sequence_map` for the `Has author` property the expected author sequence is produced on all platforms equally
```
1) SRF\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest::testCaseFile with data set "bibtex-01.json" ('/home/travis/build/SemanticMe...1.json')
Failed "#2 `format=bibtex` multiple authors (bibtex-01-2.bib)" for StringContains:
==== (actual) ====
@Book{stegun1964homf,
address = "New York",
author = "Irene A. Stegun and …
```
> Use `sequence_map` for author/bibtex test

- src/Graph/GraphOptions.php
This PR is made in reference to: https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/538
- Remove doc types from fields in GraphOptions
> Remove doc types from fields

- src/Graph/GraphPrinter.php
This PR is made in reference to:https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/538#discussion_r319732598
- Use getPreferredCaption() to get the "displaytitle" for graph nodes
> Use getPreferredCaption() to get the "displaytitle" for graph nodes

- formats/media/MediaPlayer.php
- tests/phpunit/Integration/JSONScript/Fixtures/dummy.mp3
- tests/phpunit/Integration/JSONScript/TestCases/media-01.json
- Replace deprecated MW methods
- some cleanup
- simple tests
Fixes #
> Mediaplayer: Replace deprecated methods (+ some cleanup), tests

- formats/calendar/resources/ext.srf.calendar.css
This PR is made in reference to: none
- table.navigation_table width is set to 100% but table.month_calendar is not
- This leaves a blank area below, to the right, of table.navigation_table. Also, to the right of table.month_calendar
- Set table.month_calendar width to 100%
> Calendar format: Set table.month_calendar width to 100%

- formats/Exhibit/SRF_Exhibit.php
This constant was renamed to DB_REPLICA and remained as deprecated alias since MW 1.28.
It was completely [dropped in MW 1.34](https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/443747/)
> Replace deprecated DB_SLAVE constant

- .travis.yml
- composer.json
This PR is made in reference to: #570
- moved "mediawiki/mermaid": "~2.1" from composer.json "require" to "suggest"
- updated Travis to install a compatible Mermaid version 
- attempt to temp. avoid i#567 using MW "REL1_34"
Fixes #570
> [Graph] Fix Mermaid 2.2.0 now requires MW 1.33+

- tests/phpunit/Integration/JSONScript/TestCases/gantt-01.json
This PR is made in reference to: #575 
Skip existing tests for MW > 1.32 and add new integration tests.
> MediaWiki changed handling of spaces &#160 vs. &nbsp; vs " "

- i18n/en.json
- Provides missen "srf-paramdesc-liststyle" message to "valuerank" format
Fixes #
> Provide missing system message to valuerank

- formats/filtered/resources/css/ext.srf.filtered.value-filter.less
This PR is made in reference to: #587
- Fix display of tokens selectors in chrome and edge
Fixes #587
> [Filtered] Fix tokens selector

- formats/Exhibit/SRF_Exhibit.php
- formats/array/SRF_Array.php
- formats/array/SRF_Hash.php
- formats/calendar/SRF_Calendar.php
Since the minimum MW version is already set to 1.31, we can remove some
ancient back-compat code, and we know that MediaWikiServices::getParser()
will always be available.
Bug: T160811
> Replace use of deprecated $wgParser

- src/Outline/README.md
- src/Outline/TemplateBuilder.php
- a new variable {{#itemsubjectraw}}
Currently the Outline format does support
1. linking of subject items (which automatically makes use of Display Title) or 
2. unlinked subject items, showing the Display Title
If you want to use the template format in Outline you might want to look up additional fields. For this, you have to use option 2. because linked items can not be used in "ask queries". Unfortunately, option 2. does only return the Display Title, not the page title.
To solve this, this PR introduces an additional template parameter #itemsubjectraw which can be used inside the item's template for further processing.
> Add {{#itemsubjectraw}} for furhter processing

- DefaultSettings.php
Currently, SemanticResultsFormats autoloads its setup file via Composer's autoloader and exits if it does not detect a MediaWiki environment. This prevents developers from executing tools also installed via composer such as the `phpunit` binary, or `phpcs`/`phpcbf`/`phan` etc., as SemanticResultFormat will immediately exit the process. As a fix, remove the environment check; this is also consistent with how Semantic MediaWiki itself behaves since SemanticMediaWiki/SemanticMediaWiki#1732 and SemanticMediaWiki/Mermaid#47.
> Remove check for MediaWiki environment from settings file

- SemanticResultFormats.utils.php
- formats/boilerplate/SRF_Boilerplate.php
- formats/d3/SRF_D3Chart.php
- formats/dygraphs/SRF_Dygraphs.php
- formats/jqplot/SRF_jqPlotChart.php
- formats/jqplot/SRF_jqPlotSeries.php
- formats/media/MediaPlayer.php
- formats/sparkline/SRF_Sparkline.php
- formats/timeseries/SRF_Timeseries.php
The function Skin::makeVariablesScript() will be deprecated in MediaWiki 1.36. Since it's used in a lot of places in this codebase, I reimplemented it in SRF utils class, and the rest is just minimal changes to move references from the MediaWiki Skin class to the location of the new function.
https://phabricator.wikimedia.org/T257995
Fixes #
> Remove and replace usages of Skin::makeVariablesScript()

- formats/gallery/Gallery.php
This PR is made in reference to: #396
- Currently the `default` parameter is being ignored with the gallery format. I tried to address it checking if `$results` is empty and if the default parameter has been set.
Fixes #396 
This small addition works in my private wiki without errors. although I don't include a test in the commit added. I am not a PHP expert and it is my first contribution to SRF, so let me know of any possible error or improvement.
> Gallery: show default if there isn't results

- formats/jqplot/resources/ext.srf.jqplot.chart.bubble.js
Makes sure the labels are passed to the bubble chart aswel.
- bubble chart axis labels fixes
> Makes sure the axis labels are passed to the bubble chart

- src/Graph/GraphPrinter.php
Use \MediaWiki\MediaWikiServices::getInstance()->getParser() instead.
Fixes #662.
> Remove the deprecated $wgParser from src/Graph/GraphPrinter.php

- src/Graph/GraphFormatter.php
Page titles can contain double quotes. dot requires them to be escaped,
otherwise, dot is broken.
Fixes #665.
> Escape double quotes in node names

- .github/workflows/main.yml
- SemanticResultFormats.hooks.php
- SemanticResultFormats.php
- extension.json
- formats/filtered/src/Filtered.php
- formats/gallery/Gallery.php
- src/ResourceFormatter.php
- tests/bootstrap.php
- tests/phpunit/Integration/I18nJsonFileIntegrityTest.php
- tests/phpunit/Integration/JSONScript/JsonTestCaseScriptRunnerTest.php
- tests/phpunit/Unit/Formats/GalleryTest.php
- tests/phpunit/Unit/Formats/TreeTest.php
- tests/phpunit/Unit/Formats/ValueRankTest.php
- tests/phpunit/Unit/Outline/ListTreeBuilderTest.php
- tests/phpunit/Unit/Outline/OutlineResultPrinterTest.php
- tests/phpunit/Unit/Outline/TemplateBuilderTest.php
- tests/phpunit/Unit/ResourceFormatterTest.php
This PR is made in reference to: #694 (only partially, because during test executions classes are not found).
With this PR the tests will at least attempt to run, but then fail due to missing classes.
When adding the following aliases to `tests\bootstrap.php` (which I doubt is the correct way to do it):
```
class_alias( '\SMW\Tests\QueryPrinterRegistryTestCase', '\SMW\Test\QueryPrinterRegistryTestCase' );
class_alias( '\SMW\Tests\Integration\JSONScript\JSONScriptTestCaseRunnerTest', '\SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest' );
class_alias( '\SMW\Query\ResultPrinters\ResultPrinter', '\SMW\ResultPrinter' );
class_alias( '\SMW\Query\ResultPrinters\FileExportPrinter', '\SMW\FileExportPrinter' );
```
Then the result looks like this:
CI example: …
> First attempt to run tests for SMW 4 and MW 1.36/1.37

- .phpcs.xml
- DefaultSettings.php
- composer.json
Fixes #698 by using `isset()` instead of `array_key_exists()`.
-------
This PR is made in reference to: #698
- phpcs configuration
- update to composer.json to support common MW development
> Add some linting tools and fix one found problem

- composer.json
There is no code relying on this dependency.
This PR is made in reference to: #710
> Remove unused dependency to `symfony/css-selector`

- formats/datatables/resources/ext.srf.formats.datatables.js
This PR is made in reference to: https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/188#issuecomment-1127347867
fix:#188
↓
> fix Datatables (zero-based index)

- formats/filtered/src/Filtered.php
- formats/widget/resources/ext.srf.pagewidget.carousel.js
- resources/jquery/jquery.dynamiccarousel.js
fix issue https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/724 (carousel not working)
> SemanticResultFormats (KM-A)

- src/Outline/TemplateBuilder.php
- tests/phpunit/Integration/JSONScript/TestCases/outline-01.json
Similar to #600 when the parameter template= is used: the second occurence of the value was not shown.
I ran the tests locally on MW 1.35, I hope it works for other versions.
Closes: #599
> Display all values with outlineproperties (bis)

- tests/phpunit/Unit/BibTex/BibTexFileExportPrinterTest.php
- tests/phpunit/Unit/vCard/vCardFileExportPrinterTest.php
This was deactivated in 670487bd3214 but it works now (at least when tested locally on MW 1.35 + SMW master + SRF master). I guess the version of PHPUnit changed and/or the tests in SMW were improved.
> Reactivate 12 skipped tests on PHP 7.4

- tests/phpunit/Unit/Formats/GalleryTest.php
- tests/phpunit/Unit/Outline/OutlineResultPrinterTest.php
[Relevant doc for PHPUnit](https://phpunit.readthedocs.io/en/9.5/test-doubles.html) : `addMethods()` is used when the method does not exist (which is the case here) and `onlyMethods()` when the method exists. This fixes the 2 tests marked as 'warning'.
> Use addMethods instead of onlyMethods when mocking stdClass

- formats/graphviz/README
- formats/graphviz/SRF_Process.php
- src/Graph/GraphFormatter.php
- src/Graph/GraphPrinter.php
- tests/phpunit/Unit/Graph/GraphFormatterTest.php
The [GraphViz](https://www.mediawiki.org/wiki/Extension:GraphViz) extension is unmaintained and not working with MW versions newer then 1.32. [Diagrams ](https://www.mediawiki.org/wiki/Extension:Diagrams) seems to do the same, and is working properly. We've tested it and came to the conclusion that Diagrams is a good replacement.
> Replacing unmaintained extension GraphViz with Diagrams

- Resources.php
AFAIK, a group is unnecessary and causes ResourceLoader not to merge the stylesheet with the rest, thus causing an extra web request only to get the CSS for this extension.
This inefficiency is reported by https://www.webpagetest.org as well as https://developers.google.com/speed and NewRelic
> Remove group from styles resource

- docs/COMPATIBILITY.md
Update based on https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/607a2a339d53156bd24739b2a7e6a7caa85cbde3 and considering the time the version was released
> Update compatibility information

- formats/datatables/resources/ext.srf.formats.datatables.js
Fixes a little inconsistency due to cacheKey in conjunction with searchPanes
Updates the following PR: https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/774
> (Datatables-v2) Fixes Ajax navigation

- src/ResourceFormatter.php
fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/764
***attention! the proposed solution is a workaround for the use with SRF's `ext.srf.api.query.js -> toList` (a regex to match the printout label and custom label), however a preferred solution would be at SMW level trying to fix PrintRequest's `Serializer -> doSerializeProp`
> preferred label and eventcalendar

- formats/jqplot/SRF_jqPlot.php
forces $linker to null
fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/782
> fixes issue 782 jqplotchart label error with DistributionResults and link != none

- SemanticResultFormats.php
HookContainer service is available since 1.35, just like extension.json compatibility statement, so no need of a compatibility layer.
This change is similar to [this one in CentralAuth](https://gerrit.wikimedia.org/r/c/904453).
Issue: #781
> Replace deprecated $wgHooks

- formats/carousel/Carousel.php
- formats/carousel/resources/ext.srf.formats.carousel.css
- tests/phpunit/Integration/JSONScript/TestCases/carousel-01.json
- fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/784
- fixes default arrow color
the issue was caused by 2 concurrent problems, the parameter `slick-responsive` with wrong default value prevented all subsequent parameters to work, including `slick-slidesToShow`, now all the parameters listed here https://www.semantic-mediawiki.org/wiki/Help:Carousel_format should work correctly.
It has also been implemented the suggestion of @michaelfreiberg mentioned in the same issue
> Fix issue 784 slidesToShow

- RELEASE-NOTES.md
- docs/COMPATIBILITY.md
- docs/INSTALL.md
* Provide RELEASE-NOTES
* update COMPATIBILITY
* update INSTALL
> 4.2.1 release

- formats/filtered/resources/js/ext.srf.filtered.js
- formats/filtered/resources/ts/Filtered/Filter/Filter.ts
- tests/qunit/formats/ext.srf.formats.filtered.test.js
Terms for CSS classes '**enabled**' and '**disabled**' has been updated and changed to more specific terms. 
- 'enabled'  => 'filtered-filter-enabled';
- 'disable' => 'filtered-filter-disable'
> add more specific term for CSS classes 'enabled' and 'disabled'

- formats/dygraphs/SRF_Dygraphs.php
- formats/media/MediaPlayer.php
No need to support the older method wfFindFile (pre-MW 1.34). Since SRF 4.0.x, the minimum version is MW 1.35. Also corrected an earlier oversight.
#778
> Updates to wfFindFile again

- formats/datatables/DataTables.php
Fixes issue: https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/853
i first checked how SMW handels this with broadtable and pretty much just moved this code
> fix error when using intro and outro text

- Resources.php
- formats/datatables/resources/ext.srf.formats.datatables.js
By adding `-1` to `datatables-lengthMenu`, all rows can be shown.
> Support showing all rows as a length option in DataTables

- formats/datatables/DataTables.php
- formats/datatables/resources/ext.srf.formats.datatables.css
- formats/datatables/resources/ext.srf.formats.datatables.js
> Use layout instead of dom for datatables

- formats/time/SRF_Time.php
> SRF_Time: Fix "Implicit conversion from float x to int loses precision"

- .github/workflows/ci.yml
- Makefile
- composer.json
- tests/phpunit/Integration/JSONScript/JsonTestCaseScriptRunnerTest.php
- tests/phpunit/Integration/JSONScript/TestCases/bibtex-01.json
- tests/phpunit/Integration/JSONScript/TestCases/gallery-01.json
- tests/phpunit/Integration/JSONScript/TestCases/gallery-02.json
- tests/phpunit/Integration/JSONScript/TestCases/gallery-03.json
- tests/phpunit/Unit/Formats/ArrayTest.php
- tests/phpunit/Unit/Formats/CarouselTest.php
- tests/phpunit/Unit/Formats/DataTablesTest.php
- tests/phpunit/Unit/Formats/DygraphsTest.php
- tests/phpunit/Unit/Formats/EventCalendarTest.php
- tests/phpunit/Unit/Formats/GalleryTest.php
- tests/phpunit/Unit/Formats/GanttTest.php
- tests/phpunit/Unit/Formats/IncomingTest.php
- tests/phpunit/Unit/Formats/ListWidgetTest.php
- tests/phpunit/Unit/Formats/MathTest.php
- tests/phpunit/Unit/Formats/MediaPlayerTest.php
- tests/phpunit/Unit/Formats/PageWidgetTest.php
- tests/phpunit/Unit/Formats/PrologTest.php
- tests/phpunit/Unit/Formats/SparklineTest.php
- tests/phpunit/Unit/Formats/SpreadsheetTest.php
- tests/phpunit/Unit/Formats/TagCloudTest.php
- tests/phpunit/Unit/Formats/TimeseriesTest.php
- tests/phpunit/Unit/Formats/TreeTest.php
- tests/phpunit/Unit/Formats/ValueRankTest.php
- tests/phpunit/Unit/Formats/jqPlotChartTest.php
- tests/phpunit/Unit/Formats/jqPlotSeriesTest.php
- tests/phpunit/Unit/Formats/vCardTest.php
This PR is related to the issue #882.
This PR contains:
- update composer.json - add `dev-master` to `require` section
- skip few tests for MW 1.40, new issue will be opened to check registration of parser function in MW 1.40
- update `ci.yml`
- fix paths in unit and integration tests
- enable codecov upload in MW 1.40
This PR also covers the issues #876 and #880.
> Issue 882 - add support for MW 1.40, fix 4.2.0 overrule SMW dev-master

- composer.json
Partial revert of 
* https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/884
Packagist sent me a notification that composer.json is no longer valid.
> Revert dev-master addition

- composer.json
This PR is related to the issue #889.
This PR contains:
- `composer.json` updated
- `"mediawiki/semantic-media-wiki": "@dev"` added to `require-dev` section
- CI for MW 1.39 and 1.40 works as it should. 
- codecov upload works perfect, that is covered as a part of MW 1.40
> Issue 889 - update composer.json, fix codecov upload and support for MW 1.40

- src/iCalendar/DateParser.php
> Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/extensions/SemanticResultFormats/src/iCalendar/DateParser.php on line 33
> DateParser: Fix "str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated"

- formats/datatables/Api.php
Create a page with following content
```
{{#subobject: A |Text=A }}
{{#subobject: B |Text=B }}
{{#subobject: C |Text=C }}
{{#ask:
[[-Has subobject::{{FULLPAGENAME}}]]
|?Has subobject.Text
|format=datatables
|datatables-pageLength=2
|limit=1
}}
```
When SMW renders the page, `Processing...` and `Loading...` stays displayed.
Following is the response from api action=`ext.srf.datatables.api`, in browser devtool.
```json
{
"error": {
"code": "internal_api_error_InvalidArgumentException",
"info": "[3f28f227f0de38a93bb53121] Exception caught: Data provided for print request does not fit the type of printout.",
"errorclass": "InvalidArgumentException",
"*": "InvalidArgumentException at /var/www/html/extensions/SemanticMediaWiki/src/Query/PrintRequest.php(98)\nfrom …
```
> Add CHAIN field support in datatables ajax API

- formats/datatables/Api.php
- formats/datatables/DataTables.php
- formats/datatables/Hooks.php
- formats/datatables/resources/ext.srf.formats.datatables.js
* removes parameter `defer-each` (set default limit to 100 and retrieve all rows until the limit both on page load and via Ajax)
* redesign client-side cache mechanism to correctly handle non-subsequent pages and to take advantage from the retrieved rows against table page length
(test further before merging)
> Datatables redesign client side cache mechanism

- formats/datatables/DataTables.php
> make DataTables:getCellContent() a public function again

- SemanticResultFormats.hooks.php
- SemanticResultFormats.utils.php
- formats/gallery/Gallery.php
* "srfVersion" is not used anywhere.
* "srfgScriptPath" used but never via mw.config.get().
Instead, the onResourceLoaderGetConfigVars hook adds 'srf-config' (which includes a srfgScriptPath subkey) to mw.config.get(). Then, ext.stf.js uses this to implement srf.settings.get(), which is what various JavaScript files use to read srfgScriptPath.
The global "srfgScriptPath" key is not used anywhere.
> Remove unused addGlobalJSVariables()

- formats/incoming/SRF_Incoming.php
Fix for #614. When no template is used, removes the html (a div element with the 'srf-incoming' class) from the result so that it allows for further reuse.
> Fix for #614

- tests/phpunit/Integration/JSONScript/README.md
- tests/phpunit/Integration/JSONScript/ReadmeContentsBuilder.php
This PR is related to the issue #932.
This PR contains:
- updated the documentation for JSONScript usage in SRF
- ensured consistency with the improvements made in SMW
- added script to update the list of test cases for JSONScript tests
> Issue 932 - improve docs about JSONScript

- RELEASE-NOTES.md
Per https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/928#issuecomment-2762711538
@thomas-topway-it would you be able to review the notes please?
I am new to the project and I am unfamiliar with some of the changes that you made.
It would be awesome if you can take a look.
> Update DataTables release notes for 5.0.0 release

- .github/workflows/ci.yml
I don't know if we want to drop MW 1.42 or lower in this extension yet, so just pining the SMW version used for those releases to 5.1.0 for now.
> Use SMW version 5.1.0 for MW 1.39-1.42 in CI

- .github/workflows/ci.yml
- Makefile
- src/Graph/GraphFormatter.php
- src/Graph/GraphNode.php
- src/Graph/GraphOptions.php
- src/Graph/GraphPrinter.php
- tests/phpunit/Unit/Graph/GraphFormatterTest.php
This PR is related to the issue #954.
Currently, when using `graphfields=yes`, only `non-Page` properties (e.g., strings, dates) are displayed in the graph node info table.
This PR introduces a new optional parameter `graphfieldspages=` with the following behavior:
- When `graphfieldspages=no` (default):
- All Page-type properties are rendered as graph nodes (edges), and none appear as node fields.
- When `graphfieldspages=yes`:
- For each Page-type property per node:
- The first Page property is rendered only as a node (edge), not as a field.
- Any additional Page properties are rendered only as fields in the node info table, not as separate nodes.
This PR also:
- Adds a test case to verify the new behavior of `graphfieldspages`.
- Updates the CI configuration to use the latest stable …
> Issue 954 - add graphfieldspages param to optionally include Page-type values as node fields

- formats/filtered/src/View/MapView.php
For 
* https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/962
Untested
> Stop using removed WikiPage::factory

- formats/datatables/SearchPanes.php
-- considers this https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/942
-- fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/910
-- uses structured queries instead of raw joins in the from clause
> use structured queries
