formats/tagcloud/TagCloud.php

Might fix https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/116

Some cleanup in TagCloud

---

formats/calendar/SRF_Calendar.php

I ran into some problems where various bits here were undefined when
running SMW's rebuildData.

Update SRF to use Contexts

---

formats/calendar/SRF_Calendar.php

Addresses an issue discovered on #118

Long lines are needed b/c of html leaks

---

formats/calendar/SRF_Calendar.php

Fixes #142
See https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/142

Fix exception from SRF_Calendar.php

---

formats/array/SRF_Array.php

Follow up: I02051f0c74b4db93093f171f1250c03b99f6cec6 (https://gerrit.wikimedia.org/r/#/c/263908/1)

Add compatibility for MediaWiki 1.19

---

formats/media/MediaPlayer.php
formats/media/resources/ext.srf.formats.media.js

http://wikimedia.7.x6.nabble.com/SRF-Media-Format-td5059068.html

Support URL links in media format

---

formats/timeseries/SRF_Timeseries.php

Fix timeseries format with 0, refs #145

---

RELEASE-NOTES.md
SemanticResultFormats.php
formats/excel/SRF_Excel.php
i18n/en.json
i18n/qqq.json

* Use arrays instead of ParamDefinition objects
* Provide parameter descriptions
Set version to 2.4-alpha

Fix Special:Ask param descriptions for the excel format

---

.travis.yml
build/travis/install-mediawiki.sh

to avoid MW Bug T135102 (https://phabricator.wikimedia.org/T135102)

Bump test version MW 1.25.1 => 1.25.6

---

formats/datatables/resources/ext.srf.formats.datatables.js
tests/qunit/formats/ext.srf.formats.datatables.test.js

Fixes #172, regression test included.

Fixed datatables handling of empty printouts.

---

INSTALL.md
README.md
RELEASE-NOTES.md
SemanticResultFormats.php

https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/164

2.4.0 release

---

INSTALL.md
SemanticResultFormats.php

Refs also: https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/c7fbe14fd1ec6437fa5bf8daed32611aad0a9cdd#commitcomment-19443678

Amend some typos

---

Resources.php
formats/slideshow/resources/ext.srf.slideshow.js

Also
* add missing dependency on mw.util
* add some error handling
This fixes issue #137.

Remove dependency on mediawiki.legacy.ajax library

---

RELEASE-NOTES.md
SemanticResultFormats.php

Add notes about the 2.4.2 release

Release version 2.4.2

---

INSTALL.md
README.md
RELEASE-NOTES.md
SemanticResultFormats.php

Updated documentation to reflect the changes for this new branch.
Refs: https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/190

Move on to SRF 2.5.0-alpha

---

resources/ext.srf.util.html.js

fixes issue #199

---

formats/math/SRF_Math.php

Fixes #135

---

Resources.php
formats/calendar/EventCalendar.php
formats/calendar/resources/ext.srf.formats.eventcalendar.js
i18n/de.json
i18n/en.json

to allow e.g. opening a form in edit mode when clicking on an calendar day. See commit messages for details.

eventcalendar format / added clicktarget parameter

---

.travis.yml
composer.json

* Bumped PHP minimum requirement to 5.5+
* Made linkfixes
* Applied several tweaks
Refs: https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/190#issuecomment-303799107

Bump minimum PHP requirement to 5.5+

---

Resources.php
phpunit.xml.dist

- Always run ResourcesTest
- fix jplayer file path

Always run ResourcesTest; fix jplayer file path

---

i18n/en.json
i18n/qqq.json

This PR is made in reference to: missing system message
- See https://sandbox.semantic-mediawiki.org/wiki/Smwdoc_-_incoming

I18nincoming

---

DefaultSettings.php
INSTALL.md
README.md
RELEASE-NOTES.md
build/travis/install-semantic-result-formats.sh
composer.json

* remove temporary package installations from travis build script
* do not load filtered by default (it loads map data from external page)
* polish INSTALL.MD
* add changes to RELEASE-NOTES.md
This PR is made in reference to: #190 

Cleanup, polish install instructions, add to release notes

---

DefaultSettings.php
INSTALL.md
RELEASE-NOTES.md
SemanticResultFormats.php
composer.json

This PR is made in reference to: #190 
- Provides the 2.5.0 release
- Updated RELEASE-NOTES
- Updated INSTALL

Make 2.5.0 release

---

tests/phpunit/Unit/Formats/TreeTest.php

This PR is made in reference to: #226 
- Restore global state after test execution

Fix tree test

---

RELEASE-NOTES.md
SemanticResultFormats.php
composer.json

This PR is made in reference to: #258 
- Provides RELEASE-NOTES

Make 2.5.1 release

---

RELEASE-NOTES.md
formats/filtered/resources/js/ext.srf.filtered.js
formats/filtered/resources/ts/Filtered/View/MapView.ts
formats/filtered/src/View/MapView.php
formats/filtered/tests/qunit/Filtered/View/MapViewTest.ts
formats/filtered/tests/qunit/Filtered/View/ViewTest.ts
formats/filtered/tests/qunit/Filtered/ViewSelectorTest.ts
formats/filtered/tests/qunit/bootstrap.ts
tests/qunit/formats/ext.srf.formats.filtered.test.js

This PR is made in reference to: #238
* New parameters: map view zoom, map view min zoom, map view max zoom
* Initial QUnit tests for View and MapView classes

Filtered - map view: New parameters, improved testing

---

INSTALL.md
RELEASE-NOTES.md
SemanticResultFormats.php

This PR is made in reference to: #271 
- Provides RELEASE-NOTES for 2.5.2
- Bumps version to 2.5.2

Make 2.5.2 release

---

Resources.php
SemanticResultFormats.hooks.php
SemanticResultFormats.php
i18n/en.json
resources/ext.srf.css

This PR is made in reference to: # https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2714

Use `SMW::GetPreferences`

---

formats/gallery/Gallery.php

This PR is made in reference to: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2748

Remove ContextSource reference

---

formats/tagcloud/TagCloud.php
tests/phpunit/Integration/JSONScript/TestCases/tagcloud-01.json

This PR is made in reference to: #325, #315
- Caused by #315
- Adds a simple integration test to validate the HTML output and guard against #325
Fixes: #325

Fix title reference, refs 325, 315

---

INSTALL.md
RELEASE-NOTES.md
SemanticResultFormats.php

This PR is made in reference to: #290 
-  Bumps version
-  Provides information on new version

2.5.3 release

---

SemanticResultFormats.php
src/vCard/vCardFileExportPrinter.php
tests/phpunit/Unit/Formats/vCardTest.php

This PR is made in reference to: #314

Tidy (vCardFileExportPrinter)

---

INSTALL.md
RELEASE-NOTES.md
SemanticResultFormats.php

This PR is made in reference to: #348 
- Bumps version
- Provides information on new version

2.5.4 release

---

formats/tagcloud/TagCloud.php

This PR is made in reference to: #355

Fix missing namespace in result

---

SemanticResultFormats.php
composer.json
formats/filtered/package.json

- Update license identifier to match SPDX v3.0

Update license identifier to match SPDX v3.0 

---

INSTALL.md
RELEASE-NOTES.md
SemanticResultFormats.php

This PR is made in reference to: #367 
- Release notes for the new release

2.5.5 release

---

resources/jquery/jqplot/jquery.jqplot.js

https://phabricator.wikimedia.org/T201491

Fix 'wierd' typo

---

resources/jquery/jqplot/jquery.jqplot.js

https://phabricator.wikimedia.org/T201491

Fix 'Mehtods' typo

---

formats/slideshow/SRF_SlideShowApi.php

https://phabricator.wikimedia.org/T201491

Fix 'functon' typo

---

formats/tree/TreeResultPrinter.php

https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/390

Attempt to fix failing test

---

formats/array/SRF_Array.php

Stop using deprecated newDataItemValue

---

formats/dygraphs/SRF_Dygraphs.php

Stop using deprecated makePageFromTitle

---

formats/array/SRF_Array.php

Remove unused constructor argument

---

formats/time/SRF_Time.php

Stop using deprecated method in SRFTime

---

formats/graphviz/SRF_Process.php
formats/jqplot/SRF_jqPlotSeries.php
formats/outline/SRF_Outline.php
formats/tagcloud/TagCloud.php
formats/timeline/SRF_Timeline.php
formats/timeseries/SRF_Timeseries.php
formats/tree/TreeResultPrinter.php

Remove unused code

---

INSTALL.md
RELEASE-NOTES.md
SemanticResultFormats.php

This PR is made in reference to: #429 
- RELEASE-NOTES

2.5.6 release

---

RELEASE-NOTES.md
docs/INSTALL.md

This PR is made in reference to: #429 
- RELEASE-NOTES

Provide information about version 2.5.6 to master

---

SemanticResultFormats.php
build/travis/install-semantic-result-formats.sh
extension.json

Switch to extension registration mechanism

---

README.md
RELEASE-NOTES.md
composer.json
docs/INSTALL.md
extension.json

This PR is made in reference to: #439
- Updated documenation
- Updated RELEASE-NOTES
- Updated version requirements

Release version 3.0.0

---

Resources.php

Ref https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3823.

Use SMW copy of jquery.async

---

RELEASE-NOTES.md
docs/INSTALL.md
extension.json

This PR is made in reference to: #470
* Update RELEASE-NOTES.md for new release
* Update INSTALL.md for new release
* Update extension.json for new release
Fixes #

Release version 3.0.1

---

tests/phpunit/Integration/JSONScript/TestCases/filtered-01.json
tests/phpunit/Integration/JSONScript/TestCases/filtered-02.json

- Fix JSON script tests of Filtered format for MW parser evolution
Fixes #

Filtered: Fix JSON script tests for MW 1.33 parser evolution

---

.travis.yml

[CI] Change MW release to REL1_31+

---

src/Outline/OutlineTree.php

This PR is made in reference to: #499
Fixes #499

`OutlineTree` to check for null, refs 499

---

DefaultSettings.php
SemanticResultFormats.php
src/Graph/GraphPrinter.php
tests/phpunit/Unit/Formats/GraphTest.php

This PR is made in reference to: #503
- Moves graph format to "src/",
- Addes namespace "SRF" 

Move Graph format to "src/", added namespace "SRF" (#297)

---

.travis.yml

This PR is made in reference to: #478

[CI] Make PHP 7.2 temporary non-voting

---

formats/bibtex/SRF_BibTeX.php
src/BibTex/Item.php
tests/phpunit/Integration/JSONScript/Fixtures/bibtex-01-1.bib
tests/phpunit/Integration/JSONScript/Fixtures/bibtex-01-3.bib
tests/phpunit/Unit/BibTex/ItemTest.php

- Isolates text formatting and field collection using a separate `Item` class
- Adds the `filename` parameter (https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/371#issuecomment-367017087)

Tidy `format=bibtex`

---

tests/phpunit/Unit/BibTex/BibTexFileExportPrinterTest.php
tests/phpunit/Unit/vCard/vCardFileExportPrinterTest.php

This PR is made in reference to: #510, #459

Extend unit tests (bibtex, vcard)

---

SemanticResultFormats.php
src/Outline/OutlineResultPrinter.php
tests/phpunit/Unit/Outline/OutlineResultPrinterTest.php

This PR is made in reference to: #458

Move SRFOutline class, refs 458

---

SemanticResultFormats.php
composer.json

Refs: https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/445

Make SRF installable without ext php-gd

---

formats/spreadsheet/SpreadsheetPrinter.php

This PR is made in reference to: #524
This PR addresses or contains: 
- Declare undefined variable 
Fixes #524

Fix #524: Declare undefined variable

---

formats/filtered/src/View/TableView.php

This PR is made in reference to: #478
- Remove usage of each()
Fixes #478

Fix #478: Remove usage of each()

---

formats/slideshow/SRF_SlideShowApi.php

https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3402

Stop using deprecated function

---

composer.json
extension.json

- Update meta files for 3.2.0-alpha
Fixes #

Start 3.2.0 development

---

docs/INSTALL.md

* add note about gantt
* change from excel to spreadsheet
Fixes #
[skip ci]

Tweak installation file

---

.travis.yml
composer.json

As per https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/docs/COMPATIBILITY.md

Bump PHP to ~7.1

---

src/iCalendar/iCalendarFileExportPrinter.php

[ical] Tidy (iCalendarFileExportPrinter)

---

src/Graph/GraphPrinter.php

This PR is made in reference to: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4273
- Preparation to rely on `ResultPrinterDependency` once SMW 3.1 becomes mandatory

[Graph] Check external dependency

---

src/Graph/GraphFormatter.php
src/Graph/GraphNode.php

This PR is made in reference to: #556
- fixed Undefined variable: nodeLabel when running rebuildData
Fixes #556

[Graph] fixed #556, code formatting

---

src/Outline/OutlineResultPrinter.php
src/Outline/README.md
src/Outline/TemplateBuilder.php
tests/phpunit/Integration/JSONScript/TestCases/outline-01.json
tests/phpunit/Integration/JSONScript/TestCases/outline-02.json
tests/phpunit/Unit/Outline/OutlineResultPrinterTest.php
tests/phpunit/Unit/Outline/TemplateBuilderTest.php

This PR is made in reference to: #578
This PR contains:
- add intro-/outrotempalte for outline format
Fixes #578

Add intro-/outrotemplate

---

formats/tagcloud/TagCloud.php
formats/valuerank/SRF_ValueRank.php

- avoid missing system messages for `#docinfo`
Fixes #

Reuse parameter descriptions provided by SMW

---

tests/bootstrap.php

Tidy (bootstrap)

---

formats/valuerank/SRF_ValueRank.php

This PR is made in reference to: 5de348620d117fdf92c95d9e987e54148e6b247c
- ...
- ...
- ...
Fixes #602

Check that getDataItem() returns something before calling getTitle()

---

formats/math/SRF_Math.php
tests/phpunit/Integration/JSONScript/TestCases/math-01.json

This PR is made in reference to: https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/604
- small spelling mistakes
- added integraton tests
We could not test the integraton test due to our lacking test environment...

integration tests for math/statistical formats

---

.travis.yml
build/travis/install-semantic-result-formats.sh
tests/phpunit/Unit/BibTex/BibTexFileExportPrinterTest.php
tests/phpunit/Unit/Formats/TreeTest.php
tests/phpunit/Unit/Graph/GraphFormatterTest.php
tests/phpunit/Unit/Outline/OutlineResultPrinterTest.php
tests/phpunit/Unit/iCalendar/DateParserTest.php
tests/phpunit/Unit/iCalendar/IcalFormatterTest.php
tests/phpunit/Unit/iCalendar/IcalTimezoneFormatterTest.php
tests/phpunit/Unit/vCard/vCardFileExportPrinterTest.php

@JeroenDeDauw ... includes your changes from #616

Fixes for Travis

---

formats/filtered/src/View/ListView.php
i18n/en.json
i18n/qqq.json
tests/phpunit/Integration/JSONScript/TestCases/filtered-03.json

This PR is made in reference to: #629 
- added "list view userparam" to support SMW's #userparam
Fixes #629

[Filtered] added "list view userparam"

---

tests/phpunit/Integration/JSONScript/TestCases/gallery-03.json
tests/phpunit/Unit/Formats/GalleryTest.php

Add PHPUnit + Integration tests for "gallery" format

---

tests/phpunit/Integration/JSONScript/TestCases/valuerank-01.json
tests/phpunit/Unit/Formats/ValueRankTest.php

Add unit tests for `valuerank` format

---

.travis.yml

This PR is made in reference to: #650
Fixes #650

Travis: use SMW 3.2.3

---

.github/workflows/main.yml
README.md
codecov.yml

This PR is made in reference to: #677

first attempt to support GitHub Actions

---

tests/qunit/ext.srf.test.js
tests/qunit/ext.srf.util.test.js
tests/qunit/formats/ext.srf.formats.datatables.test.js
tests/qunit/formats/ext.srf.formats.eventcalendar.tests.js
tests/qunit/formats/ext.srf.formats.gallery.test.js
tests/qunit/formats/ext.srf.formats.media.test.js
tests/qunit/formats/ext.srf.formats.tagcloud.test.js
tests/qunit/widgets/ext.srf.widgets.eventcalendar.tests.js
tests/qunit/widgets/ext.srf.widgets.optionslist.test.js
tests/qunit/widgets/ext.srf.widgets.panel.test.js
tests/qunit/widgets/ext.srf.widgets.parameters.test.js

This PR is made in reference to: #652
Fixes #652

Make qunit tests v2 compatible

---

.github/workflows/main.yml
formats/filtered/src/ResultItem.php
tests/phpunit/Unit/Filtered/ResultItemTest.php

This PR is made in reference to: #568
Fixes #568

Fix filtered format for UCA collations

---

composer.json

This PR is made in reference to: https://github.com/SemanticMediaWiki/SemanticScribunto/issues/77#issuecomment-1015796985
- Also allow installation with SMW 4.0
Fixes #

Also allow SMW 4.0

---

.github/workflows/main.yml

Run CI for MW 1.35 with SMW 4.0.0

[CI] MW 1.35 with SMW 4.0.0

---

extension.json

Fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/682

Require MW 35+ and bump version

---

src/Outline/ListTreeBuilder.php
tests/phpunit/Integration/JSONScript/TestCases/outline-02.json

This PR is made in reference to: #599
Fixes #599

Display all values with outlineproperties

---

i18n/en.json

Replace Javascript with JavaScript for consistency with other messages

i18n: replace Javascript with JavaScript

---

tests/phpunit/Unit/Filtered/ResultItemTest.php

Only used in a test.
PS: thanks @gesinn-it-gea for the CI on 1.38 :)

Support new service CollationFactory of MW 1.37+

---

extension.json

Yeah, the new datatables format is part of it. :)

Start 4.1.0 release

---

formats/dygraphs/SRF_Dygraphs.php

See #778 
Replace wfFindFile and retain backwards compatibility with MW34-

Replace wfFindFile

---

src/ResourceFormatter.php

Include nonce for inline script if applicable

---

SemanticResultFormats.php
extension.json

See https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/794

Move registerHooks to onExtensionRegistration to prevent logspam

---

Resources.php

Added jqplot/resources/ext.srf.jqplot.chart.bubble.js inside the ext.srf.jqplot.chart resource, since its required inside the code.

Update Resources.php => Require bubble for Chart

---

src/Graph/GraphPrinter.php

Document graphfields param

---

.phpcs.xml
formats/datatables/Api.php
formats/datatables/Hooks.php
formats/slideshow/SRF_SlideShowApi.php

Fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/842 and https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/843.

Fix incorrect references to Semantic MediaWiki configuration values

---

formats/filtered/src/Filters/DistanceFilter.php
formats/filtered/src/Filters/NumberFilter.php
formats/filtered/src/View/MapView.php

Replaces:
* SMWPropertyValue -> SMW\DataValues\PropertyValue

Fix class imports

---

composer.json

This brings it in line with SMW and with the CI

Raise PHP version requirement

---

formats/filtered/src/Filtered.php
formats/filtered/src/View/ListView.php

add sep parameter for listView in filtered format
-fixes https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/363

Add filtered sep
